input("Press Enter to start")
choice = int(input("What topic do you want to discuss? \n1-Addition; \n2-subtraction; \n3-multiplication; \n4-division"))
if choice == 1:
    ...
elif choice == 2:
    ...
elif choice == 3:
    ...
else:
    ...

